namespace App.Module2.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Reindex : DbMigration
    {
        public override void Up()
        {
            AlterColumn("Module2.Bodies", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.Bodies", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.Bodies", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.BodyAlias", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyAlias", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyAlias", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.BodyCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyCategories", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.BodyChannels", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyChannels", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyChannels", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.BodyClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.BodyProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.BodyProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.EducationOrganisations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.EducationOrganisations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.EducationOrganisations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolAuthorities", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolDeciles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolDeciles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolDeciles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolEducationRegions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolEducationRegions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolEducationRegions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolGenders", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolGenders", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolGeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolGeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolGeneralElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolMaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolMaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolMaoriElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolRegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolRegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolRegionalCouncils", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module2.SchoolTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module2.SchoolTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            CreateIndex("Module2.Bodies", "RecordState", name: "IX_Body_RecordState");
            CreateIndex("Module2.Bodies", "LastModifiedOnUtc", name: "IX_Body_LastModifiedOnUtc");
            CreateIndex("Module2.Bodies", "LastModifiedByPrincipalId", name: "IX_Body_LastModifiedByPrincipalId");
            CreateIndex("Module2.BodyAlias", "RecordState", name: "IX_BodyAlias_RecordState");
            CreateIndex("Module2.BodyAlias", "LastModifiedOnUtc", name: "IX_BodyAlias_LastModifiedOnUtc");
            CreateIndex("Module2.BodyAlias", "LastModifiedByPrincipalId", name: "IX_BodyAlias_LastModifiedByPrincipalId");
            CreateIndex("Module2.BodyCategories", "RecordState", name: "IX_BodyCategory_RecordState");
            CreateIndex("Module2.BodyCategories", "LastModifiedOnUtc", name: "IX_BodyCategory_LastModifiedOnUtc");
            CreateIndex("Module2.BodyCategories", "LastModifiedByPrincipalId", name: "IX_BodyCategory_LastModifiedByPrincipalId");
            CreateIndex("Module2.BodyChannels", "RecordState", name: "IX_BodyChannel_RecordState");
            CreateIndex("Module2.BodyChannels", "LastModifiedOnUtc", name: "IX_BodyChannel_LastModifiedOnUtc");
            CreateIndex("Module2.BodyChannels", "LastModifiedByPrincipalId", name: "IX_BodyChannel_LastModifiedByPrincipalId");
            CreateIndex("Module2.BodyClaims", "RecordState", name: "IX_BodyClaim_RecordState");
            CreateIndex("Module2.BodyClaims", "LastModifiedOnUtc", name: "IX_BodyClaim_LastModifiedOnUtc");
            CreateIndex("Module2.BodyClaims", "LastModifiedByPrincipalId", name: "IX_BodyClaim_LastModifiedByPrincipalId");
            CreateIndex("Module2.BodyProperties", "RecordState", name: "IX_BodyProperty_RecordState");
            CreateIndex("Module2.BodyProperties", "LastModifiedOnUtc", name: "IX_BodyProperty_LastModifiedOnUtc");
            CreateIndex("Module2.BodyProperties", "LastModifiedByPrincipalId", name: "IX_BodyProperty_LastModifiedByPrincipalId");
            CreateIndex("Module2.EducationOrganisations", "RecordState", name: "IX_EducationOrganisation_RecordState");
            CreateIndex("Module2.EducationOrganisations", "LastModifiedOnUtc", name: "IX_EducationOrganisation_LastModifiedOnUtc");
            CreateIndex("Module2.EducationOrganisations", "LastModifiedByPrincipalId", name: "IX_EducationOrganisation_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolAuthorities", "RecordState", name: "IX_SchoolAuthority_RecordState");
            CreateIndex("Module2.SchoolAuthorities", "LastModifiedOnUtc", name: "IX_SchoolAuthority_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolAuthorities", "LastModifiedByPrincipalId", name: "IX_SchoolAuthority_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolDeciles", "RecordState", name: "IX_SchoolDecile_RecordState");
            CreateIndex("Module2.SchoolDeciles", "LastModifiedOnUtc", name: "IX_SchoolDecile_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolDeciles", "LastModifiedByPrincipalId", name: "IX_SchoolDecile_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolDefinitions", "RecordState", name: "IX_SchoolDefinition_RecordState");
            CreateIndex("Module2.SchoolDefinitions", "LastModifiedOnUtc", name: "IX_SchoolDefinition_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolDefinitions", "LastModifiedByPrincipalId", name: "IX_SchoolDefinition_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolEducationRegions", "RecordState", name: "IX_SchoolEducationRegion_RecordState");
            CreateIndex("Module2.SchoolEducationRegions", "LastModifiedOnUtc", name: "IX_SchoolEducationRegion_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolEducationRegions", "LastModifiedByPrincipalId", name: "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolGenders", "RecordState", name: "IX_SchoolGender_RecordState");
            CreateIndex("Module2.SchoolGenders", "LastModifiedOnUtc", name: "IX_SchoolGender_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolGenders", "LastModifiedByPrincipalId", name: "IX_SchoolGender_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolGeneralElectorates", "RecordState", name: "IX_SchoolGeneralElectorate_RecordState");
            CreateIndex("Module2.SchoolGeneralElectorates", "LastModifiedOnUtc", name: "IX_SchoolGeneralElectorate_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolGeneralElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolMinistryOfEducationLocalOffices", "RecordState", name: "IX_SchoolMinistryOfEducationLocalOffice_RecordState");
            CreateIndex("Module2.SchoolMinistryOfEducationLocalOffices", "LastModifiedOnUtc", name: "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", name: "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolMaoriElectorates", "RecordState", name: "IX_SchoolMaoriElectorate_RecordState");
            CreateIndex("Module2.SchoolMaoriElectorates", "LastModifiedOnUtc", name: "IX_SchoolMaoriElectorate_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolMaoriElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolRegionalCouncils", "RecordState", name: "IX_SchoolRegionalCouncil_RecordState");
            CreateIndex("Module2.SchoolRegionalCouncils", "LastModifiedOnUtc", name: "IX_SchoolRegionalCouncil_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolRegionalCouncils", "LastModifiedByPrincipalId", name: "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "RecordState", name: "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_RecordState");
            CreateIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedOnUtc", name: "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", name: "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            CreateIndex("Module2.SchoolTypes", "RecordState", name: "IX_SchoolType_RecordState");
            CreateIndex("Module2.SchoolTypes", "LastModifiedOnUtc", name: "IX_SchoolType_LastModifiedOnUtc");
            CreateIndex("Module2.SchoolTypes", "LastModifiedByPrincipalId", name: "IX_SchoolType_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Module2.SchoolTypes", "IX_SchoolType_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolTypes", "IX_SchoolType_LastModifiedOnUtc");
            DropIndex("Module2.SchoolTypes", "IX_SchoolType_RecordState");
            DropIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedOnUtc");
            DropIndex("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_RecordState");
            DropIndex("Module2.SchoolRegionalCouncils", "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolRegionalCouncils", "IX_SchoolRegionalCouncil_LastModifiedOnUtc");
            DropIndex("Module2.SchoolRegionalCouncils", "IX_SchoolRegionalCouncil_RecordState");
            DropIndex("Module2.SchoolMaoriElectorates", "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolMaoriElectorates", "IX_SchoolMaoriElectorate_LastModifiedOnUtc");
            DropIndex("Module2.SchoolMaoriElectorates", "IX_SchoolMaoriElectorate_RecordState");
            DropIndex("Module2.SchoolMinistryOfEducationLocalOffices", "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolMinistryOfEducationLocalOffices", "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedOnUtc");
            DropIndex("Module2.SchoolMinistryOfEducationLocalOffices", "IX_SchoolMinistryOfEducationLocalOffice_RecordState");
            DropIndex("Module2.SchoolGeneralElectorates", "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolGeneralElectorates", "IX_SchoolGeneralElectorate_LastModifiedOnUtc");
            DropIndex("Module2.SchoolGeneralElectorates", "IX_SchoolGeneralElectorate_RecordState");
            DropIndex("Module2.SchoolGenders", "IX_SchoolGender_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolGenders", "IX_SchoolGender_LastModifiedOnUtc");
            DropIndex("Module2.SchoolGenders", "IX_SchoolGender_RecordState");
            DropIndex("Module2.SchoolEducationRegions", "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolEducationRegions", "IX_SchoolEducationRegion_LastModifiedOnUtc");
            DropIndex("Module2.SchoolEducationRegions", "IX_SchoolEducationRegion_RecordState");
            DropIndex("Module2.SchoolDefinitions", "IX_SchoolDefinition_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolDefinitions", "IX_SchoolDefinition_LastModifiedOnUtc");
            DropIndex("Module2.SchoolDefinitions", "IX_SchoolDefinition_RecordState");
            DropIndex("Module2.SchoolDeciles", "IX_SchoolDecile_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolDeciles", "IX_SchoolDecile_LastModifiedOnUtc");
            DropIndex("Module2.SchoolDeciles", "IX_SchoolDecile_RecordState");
            DropIndex("Module2.SchoolAuthorities", "IX_SchoolAuthority_LastModifiedByPrincipalId");
            DropIndex("Module2.SchoolAuthorities", "IX_SchoolAuthority_LastModifiedOnUtc");
            DropIndex("Module2.SchoolAuthorities", "IX_SchoolAuthority_RecordState");
            DropIndex("Module2.EducationOrganisations", "IX_EducationOrganisation_LastModifiedByPrincipalId");
            DropIndex("Module2.EducationOrganisations", "IX_EducationOrganisation_LastModifiedOnUtc");
            DropIndex("Module2.EducationOrganisations", "IX_EducationOrganisation_RecordState");
            DropIndex("Module2.BodyProperties", "IX_BodyProperty_LastModifiedByPrincipalId");
            DropIndex("Module2.BodyProperties", "IX_BodyProperty_LastModifiedOnUtc");
            DropIndex("Module2.BodyProperties", "IX_BodyProperty_RecordState");
            DropIndex("Module2.BodyClaims", "IX_BodyClaim_LastModifiedByPrincipalId");
            DropIndex("Module2.BodyClaims", "IX_BodyClaim_LastModifiedOnUtc");
            DropIndex("Module2.BodyClaims", "IX_BodyClaim_RecordState");
            DropIndex("Module2.BodyChannels", "IX_BodyChannel_LastModifiedByPrincipalId");
            DropIndex("Module2.BodyChannels", "IX_BodyChannel_LastModifiedOnUtc");
            DropIndex("Module2.BodyChannels", "IX_BodyChannel_RecordState");
            DropIndex("Module2.BodyCategories", "IX_BodyCategory_LastModifiedByPrincipalId");
            DropIndex("Module2.BodyCategories", "IX_BodyCategory_LastModifiedOnUtc");
            DropIndex("Module2.BodyCategories", "IX_BodyCategory_RecordState");
            DropIndex("Module2.BodyAlias", "IX_BodyAlias_LastModifiedByPrincipalId");
            DropIndex("Module2.BodyAlias", "IX_BodyAlias_LastModifiedOnUtc");
            DropIndex("Module2.BodyAlias", "IX_BodyAlias_RecordState");
            DropIndex("Module2.Bodies", "IX_Body_LastModifiedByPrincipalId");
            DropIndex("Module2.Bodies", "IX_Body_LastModifiedOnUtc");
            DropIndex("Module2.Bodies", "IX_Body_RecordState");
            AlterColumn("Module2.SchoolTypes", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolTypes", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolTerritorialAuthorityWithAucklandLocalBoards", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolRegionalCouncils", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolRegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolRegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolMaoriElectorates", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolMaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolMaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolMinistryOfEducationLocalOffices", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolGeneralElectorates", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolGeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolGeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolGenders", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolGenders", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolEducationRegions", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolEducationRegions", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolEducationRegions", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolDefinitions", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolDeciles", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolDeciles", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolDeciles", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolAuthorities", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.SchoolAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.SchoolAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.EducationOrganisations", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.EducationOrganisations", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.EducationOrganisations", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyProperties", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.BodyProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyProperties", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyClaims", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.BodyClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyClaims", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyChannels", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.BodyChannels", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyChannels", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyCategories", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.BodyCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyCategories", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyAlias", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.BodyAlias", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.BodyAlias", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.Bodies", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module2.Bodies", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module2.Bodies", "CreatedByPrincipalId", c => c.String(nullable: false));
        }
    }
}
