namespace App.Core.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Reindex : DbMigration
    {
        public override void Up()
        {
            RenameIndex(table: "Core.SessionOperations", name: "IX_SessionOperationLog_ControllerName", newName: "IX_SessionOperation_ControllerName");
            RenameIndex(table: "Core.SessionOperations", name: "IX_SessionOperationLog_ActionName", newName: "IX_SessionOperation_ActionName");
            AlterColumn("Core.MediaMetadatas", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.MediaMetadatas", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.MediaMetadatas", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.DataClassifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataClassifications", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Notifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Notifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Notifications", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.SessionOperations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SessionOperations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SessionOperations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Sessions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Sessions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Sessions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Principals", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Principals", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Principals", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.SystemRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SystemRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SystemRoles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalTags", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalTags", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalTags", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Tenants", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Tenants", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Tenants", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenantClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenantProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.DataTokens", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataTokens", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataTokens", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            CreateIndex("Core.MediaMetadatas", "RecordState", name: "IX_MediaMetadata_RecordState");
            CreateIndex("Core.MediaMetadatas", "LastModifiedOnUtc", name: "IX_MediaMetadata_LastModifiedOnUtc");
            CreateIndex("Core.MediaMetadatas", "LastModifiedByPrincipalId", name: "IX_MediaMetadata_LastModifiedByPrincipalId");
            CreateIndex("Core.DataClassifications", "RecordState", name: "IX_DataClassification_RecordState");
            CreateIndex("Core.DataClassifications", "LastModifiedOnUtc", name: "IX_DataClassification_LastModifiedOnUtc");
            CreateIndex("Core.DataClassifications", "LastModifiedByPrincipalId", name: "IX_DataClassification_LastModifiedByPrincipalId");
            CreateIndex("Core.Notifications", "RecordState", name: "IX_Notification_RecordState");
            CreateIndex("Core.Notifications", "LastModifiedOnUtc", name: "IX_Notification_LastModifiedOnUtc");
            CreateIndex("Core.Notifications", "LastModifiedByPrincipalId", name: "IX_Notification_LastModifiedByPrincipalId");
            CreateIndex("Core.SessionOperations", "RecordState", name: "IX_SessionOperation_RecordState");
            CreateIndex("Core.SessionOperations", "LastModifiedOnUtc", name: "IX_SessionOperation_LastModifiedOnUtc");
            CreateIndex("Core.SessionOperations", "LastModifiedByPrincipalId", name: "IX_SessionOperation_LastModifiedByPrincipalId");
            CreateIndex("Core.Sessions", "RecordState", name: "IX_Session_RecordState");
            CreateIndex("Core.Sessions", "LastModifiedOnUtc", name: "IX_Session_LastModifiedOnUtc");
            CreateIndex("Core.Sessions", "LastModifiedByPrincipalId", name: "IX_Session_LastModifiedByPrincipalId");
            CreateIndex("Core.Principals", "RecordState", name: "IX_Principal_RecordState");
            CreateIndex("Core.Principals", "LastModifiedOnUtc", name: "IX_Principal_LastModifiedOnUtc");
            CreateIndex("Core.Principals", "LastModifiedByPrincipalId", name: "IX_Principal_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalCategories", "RecordState", name: "IX_PrincipalCategory_RecordState");
            CreateIndex("Core.PrincipalCategories", "LastModifiedOnUtc", name: "IX_PrincipalCategory_LastModifiedOnUtc");
            CreateIndex("Core.PrincipalCategories", "LastModifiedByPrincipalId", name: "IX_PrincipalCategory_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalClaims", "RecordState", name: "IX_PrincipalClaim_RecordState");
            CreateIndex("Core.PrincipalClaims", "LastModifiedOnUtc", name: "IX_PrincipalClaim_LastModifiedOnUtc");
            CreateIndex("Core.PrincipalClaims", "LastModifiedByPrincipalId", name: "IX_PrincipalClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalLogins", "RecordState", name: "IX_PrincipalLogin_RecordState");
            CreateIndex("Core.PrincipalLogins", "LastModifiedOnUtc", name: "IX_PrincipalLogin_LastModifiedOnUtc");
            CreateIndex("Core.PrincipalLogins", "LastModifiedByPrincipalId", name: "IX_PrincipalLogin_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProperties", "RecordState", name: "IX_PrincipalProperty_RecordState");
            CreateIndex("Core.PrincipalProperties", "LastModifiedOnUtc", name: "IX_PrincipalProperty_LastModifiedOnUtc");
            CreateIndex("Core.PrincipalProperties", "LastModifiedByPrincipalId", name: "IX_PrincipalProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.SystemRoles", "RecordState", name: "IX_SystemRole_RecordState");
            CreateIndex("Core.SystemRoles", "LastModifiedOnUtc", name: "IX_SystemRole_LastModifiedOnUtc");
            CreateIndex("Core.SystemRoles", "LastModifiedByPrincipalId", name: "IX_SystemRole_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalTags", "RecordState", name: "IX_PrincipalTag_RecordState");
            CreateIndex("Core.PrincipalTags", "LastModifiedOnUtc", name: "IX_PrincipalTag_LastModifiedOnUtc");
            CreateIndex("Core.PrincipalTags", "LastModifiedByPrincipalId", name: "IX_PrincipalTag_LastModifiedByPrincipalId");
            CreateIndex("Core.Tenants", "RecordState", name: "IX_Tenant_RecordState");
            CreateIndex("Core.Tenants", "LastModifiedOnUtc", name: "IX_Tenant_LastModifiedOnUtc");
            CreateIndex("Core.Tenants", "LastModifiedByPrincipalId", name: "IX_Tenant_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantClaims", "RecordState", name: "IX_TenantClaim_RecordState");
            CreateIndex("Core.TenantClaims", "LastModifiedOnUtc", name: "IX_TenantClaim_LastModifiedOnUtc");
            CreateIndex("Core.TenantClaims", "LastModifiedByPrincipalId", name: "IX_TenantClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantProperties", "RecordState", name: "IX_TenantProperty_RecordState");
            CreateIndex("Core.TenantProperties", "LastModifiedOnUtc", name: "IX_TenantProperty_LastModifiedOnUtc");
            CreateIndex("Core.TenantProperties", "LastModifiedByPrincipalId", name: "IX_TenantProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.ExceptionRecords", "RecordState", name: "IX_ExceptionRecord_RecordState");
            CreateIndex("Core.ExceptionRecords", "LastModifiedOnUtc", name: "IX_ExceptionRecord_LastModifiedOnUtc");
            CreateIndex("Core.ExceptionRecords", "LastModifiedByPrincipalId", name: "IX_ExceptionRecord_LastModifiedByPrincipalId");
            CreateIndex("Core.DataTokens", "RecordState", name: "IX_DataToken_RecordState");
            CreateIndex("Core.DataTokens", "LastModifiedOnUtc", name: "IX_DataToken_LastModifiedOnUtc");
            CreateIndex("Core.DataTokens", "LastModifiedByPrincipalId", name: "IX_DataToken_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Core.DataTokens", "IX_DataToken_LastModifiedByPrincipalId");
            DropIndex("Core.DataTokens", "IX_DataToken_LastModifiedOnUtc");
            DropIndex("Core.DataTokens", "IX_DataToken_RecordState");
            DropIndex("Core.ExceptionRecords", "IX_ExceptionRecord_LastModifiedByPrincipalId");
            DropIndex("Core.ExceptionRecords", "IX_ExceptionRecord_LastModifiedOnUtc");
            DropIndex("Core.ExceptionRecords", "IX_ExceptionRecord_RecordState");
            DropIndex("Core.TenantProperties", "IX_TenantProperty_LastModifiedByPrincipalId");
            DropIndex("Core.TenantProperties", "IX_TenantProperty_LastModifiedOnUtc");
            DropIndex("Core.TenantProperties", "IX_TenantProperty_RecordState");
            DropIndex("Core.TenantClaims", "IX_TenantClaim_LastModifiedByPrincipalId");
            DropIndex("Core.TenantClaims", "IX_TenantClaim_LastModifiedOnUtc");
            DropIndex("Core.TenantClaims", "IX_TenantClaim_RecordState");
            DropIndex("Core.Tenants", "IX_Tenant_LastModifiedByPrincipalId");
            DropIndex("Core.Tenants", "IX_Tenant_LastModifiedOnUtc");
            DropIndex("Core.Tenants", "IX_Tenant_RecordState");
            DropIndex("Core.PrincipalTags", "IX_PrincipalTag_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalTags", "IX_PrincipalTag_LastModifiedOnUtc");
            DropIndex("Core.PrincipalTags", "IX_PrincipalTag_RecordState");
            DropIndex("Core.SystemRoles", "IX_SystemRole_LastModifiedByPrincipalId");
            DropIndex("Core.SystemRoles", "IX_SystemRole_LastModifiedOnUtc");
            DropIndex("Core.SystemRoles", "IX_SystemRole_RecordState");
            DropIndex("Core.PrincipalProperties", "IX_PrincipalProperty_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProperties", "IX_PrincipalProperty_LastModifiedOnUtc");
            DropIndex("Core.PrincipalProperties", "IX_PrincipalProperty_RecordState");
            DropIndex("Core.PrincipalLogins", "IX_PrincipalLogin_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalLogins", "IX_PrincipalLogin_LastModifiedOnUtc");
            DropIndex("Core.PrincipalLogins", "IX_PrincipalLogin_RecordState");
            DropIndex("Core.PrincipalClaims", "IX_PrincipalClaim_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalClaims", "IX_PrincipalClaim_LastModifiedOnUtc");
            DropIndex("Core.PrincipalClaims", "IX_PrincipalClaim_RecordState");
            DropIndex("Core.PrincipalCategories", "IX_PrincipalCategory_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalCategories", "IX_PrincipalCategory_LastModifiedOnUtc");
            DropIndex("Core.PrincipalCategories", "IX_PrincipalCategory_RecordState");
            DropIndex("Core.Principals", "IX_Principal_LastModifiedByPrincipalId");
            DropIndex("Core.Principals", "IX_Principal_LastModifiedOnUtc");
            DropIndex("Core.Principals", "IX_Principal_RecordState");
            DropIndex("Core.Sessions", "IX_Session_LastModifiedByPrincipalId");
            DropIndex("Core.Sessions", "IX_Session_LastModifiedOnUtc");
            DropIndex("Core.Sessions", "IX_Session_RecordState");
            DropIndex("Core.SessionOperations", "IX_SessionOperation_LastModifiedByPrincipalId");
            DropIndex("Core.SessionOperations", "IX_SessionOperation_LastModifiedOnUtc");
            DropIndex("Core.SessionOperations", "IX_SessionOperation_RecordState");
            DropIndex("Core.Notifications", "IX_Notification_LastModifiedByPrincipalId");
            DropIndex("Core.Notifications", "IX_Notification_LastModifiedOnUtc");
            DropIndex("Core.Notifications", "IX_Notification_RecordState");
            DropIndex("Core.DataClassifications", "IX_DataClassification_LastModifiedByPrincipalId");
            DropIndex("Core.DataClassifications", "IX_DataClassification_LastModifiedOnUtc");
            DropIndex("Core.DataClassifications", "IX_DataClassification_RecordState");
            DropIndex("Core.MediaMetadatas", "IX_MediaMetadata_LastModifiedByPrincipalId");
            DropIndex("Core.MediaMetadatas", "IX_MediaMetadata_LastModifiedOnUtc");
            DropIndex("Core.MediaMetadatas", "IX_MediaMetadata_RecordState");
            AlterColumn("Core.DataTokens", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.DataTokens", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.DataTokens", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.ExceptionRecords", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.ExceptionRecords", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.ExceptionRecords", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.TenantProperties", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.TenantProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.TenantProperties", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.TenantClaims", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.TenantClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.TenantClaims", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Tenants", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.Tenants", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Tenants", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalTags", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.PrincipalTags", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalTags", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.SystemRoles", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.SystemRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.SystemRoles", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalProperties", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.PrincipalProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalProperties", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalLogins", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.PrincipalLogins", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalLogins", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalClaims", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.PrincipalClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalClaims", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalCategories", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.PrincipalCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.PrincipalCategories", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Principals", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.Principals", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Principals", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Sessions", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.Sessions", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Sessions", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.SessionOperations", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.SessionOperations", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.SessionOperations", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Notifications", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.Notifications", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.Notifications", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.DataClassifications", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.DataClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.DataClassifications", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.MediaMetadatas", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Core.MediaMetadatas", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Core.MediaMetadatas", "CreatedByPrincipalId", c => c.String(nullable: false));
            RenameIndex(table: "Core.SessionOperations", name: "IX_SessionOperation_ActionName", newName: "IX_SessionOperationLog_ActionName");
            RenameIndex(table: "Core.SessionOperations", name: "IX_SessionOperation_ControllerName", newName: "IX_SessionOperationLog_ControllerName");
        }
    }
}
