namespace App.Module22.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EntitiesPrincipalLengthUpdate : DbMigration
    {
        public override void Up()
        {
            DropIndex("Module22.Courses", "IX_Course_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseDepartments", "IX_CourseDepartment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseStatus", "IX_CourseStatus_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseEnrollments", "IX_CourseEnrollment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseEnrollees", "IX_CourseEnrollee_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseGrades", "IX_CourseGrade_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorAssignments", "IX_CourseInstructorAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructors", "IX_CourseInstructor_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorOfficeAssignments", "IX_CourseInstructorOfficeAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorOffices", "IX_CourseInstructorOffice_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseRoles", "IX_CourseRole_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseOccurances", "IX_CourseOccurance_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseResourceAssignments", "IX_CourseResourceAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseResources", "IX_CourseResource_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseResourceTypes", "IX_CourseResourceType_LastModifiedByPrincipalId");
            AlterColumn("Module22.Courses", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.Courses", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.Courses", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseDepartments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseDepartments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseDepartments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseStatus", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseStatus", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseStatus", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseEnrollments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseEnrollments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseEnrollments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseEnrollees", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseEnrollees", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseEnrollees", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseGrades", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseGrades", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseGrades", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseInstructorAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseInstructors", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructors", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructors", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseInstructorOffices", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseInstructorOffices", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseRoles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseOccurances", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseOccurances", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseOccurances", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseResourceAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResourceAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResourceAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseResources", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResources", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResources", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module22.CourseResourceTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResourceTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module22.CourseResourceTypes", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            CreateIndex("Module22.Courses", "LastModifiedByPrincipalId", name: "IX_Course_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseDepartments", "LastModifiedByPrincipalId", name: "IX_CourseDepartment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseStatus", "LastModifiedByPrincipalId", name: "IX_CourseStatus_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseEnrollments", "LastModifiedByPrincipalId", name: "IX_CourseEnrollment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseEnrollees", "LastModifiedByPrincipalId", name: "IX_CourseEnrollee_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseGrades", "LastModifiedByPrincipalId", name: "IX_CourseGrade_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorAssignments", "LastModifiedByPrincipalId", name: "IX_CourseInstructorAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructors", "LastModifiedByPrincipalId", name: "IX_CourseInstructor_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorOfficeAssignments", "LastModifiedByPrincipalId", name: "IX_CourseInstructorOfficeAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorOffices", "LastModifiedByPrincipalId", name: "IX_CourseInstructorOffice_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseRoles", "LastModifiedByPrincipalId", name: "IX_CourseRole_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseOccurances", "LastModifiedByPrincipalId", name: "IX_CourseOccurance_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseResourceAssignments", "LastModifiedByPrincipalId", name: "IX_CourseResourceAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseResources", "LastModifiedByPrincipalId", name: "IX_CourseResource_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseResourceTypes", "LastModifiedByPrincipalId", name: "IX_CourseResourceType_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Module22.CourseResourceTypes", "IX_CourseResourceType_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseResources", "IX_CourseResource_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseResourceAssignments", "IX_CourseResourceAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseOccurances", "IX_CourseOccurance_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseRoles", "IX_CourseRole_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorOffices", "IX_CourseInstructorOffice_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorOfficeAssignments", "IX_CourseInstructorOfficeAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructors", "IX_CourseInstructor_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseInstructorAssignments", "IX_CourseInstructorAssignment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseGrades", "IX_CourseGrade_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseEnrollees", "IX_CourseEnrollee_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseEnrollments", "IX_CourseEnrollment_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseStatus", "IX_CourseStatus_LastModifiedByPrincipalId");
            DropIndex("Module22.CourseDepartments", "IX_CourseDepartment_LastModifiedByPrincipalId");
            DropIndex("Module22.Courses", "IX_Course_LastModifiedByPrincipalId");
            AlterColumn("Module22.CourseResourceTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseResourceTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseResourceTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseResources", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseResources", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseResources", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseResourceAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseResourceAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseResourceAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseOccurances", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseOccurances", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseOccurances", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseRoles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorOffices", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseInstructorOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorOffices", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorOfficeAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructors", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseInstructors", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructors", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseInstructorAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseInstructorAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseGrades", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseGrades", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseGrades", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseEnrollees", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseEnrollees", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseEnrollees", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseEnrollments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseEnrollments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseEnrollments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseStatus", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseStatus", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseStatus", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseDepartments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.CourseDepartments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.CourseDepartments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.Courses", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module22.Courses", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module22.Courses", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            CreateIndex("Module22.CourseResourceTypes", "LastModifiedByPrincipalId", name: "IX_CourseResourceType_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseResources", "LastModifiedByPrincipalId", name: "IX_CourseResource_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseResourceAssignments", "LastModifiedByPrincipalId", name: "IX_CourseResourceAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseOccurances", "LastModifiedByPrincipalId", name: "IX_CourseOccurance_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseRoles", "LastModifiedByPrincipalId", name: "IX_CourseRole_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorOffices", "LastModifiedByPrincipalId", name: "IX_CourseInstructorOffice_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorOfficeAssignments", "LastModifiedByPrincipalId", name: "IX_CourseInstructorOfficeAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructors", "LastModifiedByPrincipalId", name: "IX_CourseInstructor_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseInstructorAssignments", "LastModifiedByPrincipalId", name: "IX_CourseInstructorAssignment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseGrades", "LastModifiedByPrincipalId", name: "IX_CourseGrade_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseEnrollees", "LastModifiedByPrincipalId", name: "IX_CourseEnrollee_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseEnrollments", "LastModifiedByPrincipalId", name: "IX_CourseEnrollment_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseStatus", "LastModifiedByPrincipalId", name: "IX_CourseStatus_LastModifiedByPrincipalId");
            CreateIndex("Module22.CourseDepartments", "LastModifiedByPrincipalId", name: "IX_CourseDepartment_LastModifiedByPrincipalId");
            CreateIndex("Module22.Courses", "LastModifiedByPrincipalId", name: "IX_Course_LastModifiedByPrincipalId");
        }
    }
}
