namespace App.Module11.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EntitiesPrincipalLengthUpdate : DbMigration
    {
        public override void Up()
        {
            DropIndex("Module11.Bodies", "IX_Body_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyAlias", "IX_BodyAlias_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyCategories", "IX_BodyCategory_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyChannels", "IX_BodyChannel_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyClaims", "IX_BodyClaim_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyProperties", "IX_BodyProperty_LastModifiedByPrincipalId");
            DropIndex("Module11.EducationOrganisations", "IX_EducationOrganisation_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolAuthorities", "IX_SchoolAuthority_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolDeciles", "IX_SchoolDecile_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolDefinitions", "IX_SchoolDefinition_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolEducationRegions", "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolGenders", "IX_SchoolGender_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolGeneralElectorates", "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolMinistryOfEducationLocalOffices", "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolMaoriElectorates", "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolRegionalCouncils", "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolTypes", "IX_SchoolType_LastModifiedByPrincipalId");
            AlterColumn("Module11.Bodies", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.Bodies", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.Bodies", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.BodyAlias", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyAlias", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyAlias", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.BodyCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyCategories", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.BodyChannels", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyChannels", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyChannels", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.BodyClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyClaims", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.BodyProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.BodyProperties", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.EducationOrganisations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.EducationOrganisations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.EducationOrganisations", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolAuthorities", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolDeciles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolDeciles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolDeciles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolEducationRegions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolEducationRegions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolEducationRegions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolGenders", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolGenders", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolGeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolGeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolGeneralElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolMaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolMaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolMaoriElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolRegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolRegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolRegionalCouncils", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Module11.SchoolTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Module11.SchoolTypes", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            CreateIndex("Module11.Bodies", "LastModifiedByPrincipalId", name: "IX_Body_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyAlias", "LastModifiedByPrincipalId", name: "IX_BodyAlias_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyCategories", "LastModifiedByPrincipalId", name: "IX_BodyCategory_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyChannels", "LastModifiedByPrincipalId", name: "IX_BodyChannel_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyClaims", "LastModifiedByPrincipalId", name: "IX_BodyClaim_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyProperties", "LastModifiedByPrincipalId", name: "IX_BodyProperty_LastModifiedByPrincipalId");
            CreateIndex("Module11.EducationOrganisations", "LastModifiedByPrincipalId", name: "IX_EducationOrganisation_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolAuthorities", "LastModifiedByPrincipalId", name: "IX_SchoolAuthority_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolDeciles", "LastModifiedByPrincipalId", name: "IX_SchoolDecile_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolDefinitions", "LastModifiedByPrincipalId", name: "IX_SchoolDefinition_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolEducationRegions", "LastModifiedByPrincipalId", name: "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolGenders", "LastModifiedByPrincipalId", name: "IX_SchoolGender_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolGeneralElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", name: "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolMaoriElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolRegionalCouncils", "LastModifiedByPrincipalId", name: "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", name: "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolTypes", "LastModifiedByPrincipalId", name: "IX_SchoolType_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Module11.SchoolTypes", "IX_SchoolType_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolRegionalCouncils", "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolMaoriElectorates", "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolMinistryOfEducationLocalOffices", "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolGeneralElectorates", "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolGenders", "IX_SchoolGender_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolEducationRegions", "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolDefinitions", "IX_SchoolDefinition_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolDeciles", "IX_SchoolDecile_LastModifiedByPrincipalId");
            DropIndex("Module11.SchoolAuthorities", "IX_SchoolAuthority_LastModifiedByPrincipalId");
            DropIndex("Module11.EducationOrganisations", "IX_EducationOrganisation_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyProperties", "IX_BodyProperty_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyClaims", "IX_BodyClaim_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyChannels", "IX_BodyChannel_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyCategories", "IX_BodyCategory_LastModifiedByPrincipalId");
            DropIndex("Module11.BodyAlias", "IX_BodyAlias_LastModifiedByPrincipalId");
            DropIndex("Module11.Bodies", "IX_Body_LastModifiedByPrincipalId");
            AlterColumn("Module11.SchoolTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolRegionalCouncils", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolRegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolRegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolMaoriElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolMaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolMaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolMinistryOfEducationLocalOffices", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolGeneralElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolGeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolGeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolGenders", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolGenders", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolEducationRegions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolEducationRegions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolEducationRegions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolDeciles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolDeciles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolDeciles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolAuthorities", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.SchoolAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.SchoolAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.EducationOrganisations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.EducationOrganisations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.EducationOrganisations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.BodyProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.BodyClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyChannels", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.BodyChannels", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyChannels", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyCategories", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.BodyCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyAlias", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.BodyAlias", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.BodyAlias", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.Bodies", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module11.Bodies", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module11.Bodies", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            CreateIndex("Module11.SchoolTypes", "LastModifiedByPrincipalId", name: "IX_SchoolType_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolTerritorialAuthorityWithAucklandLocalBoards", "LastModifiedByPrincipalId", name: "IX_SchoolTerritorialAuthorityWithAucklandLocalBoard_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolRegionalCouncils", "LastModifiedByPrincipalId", name: "IX_SchoolRegionalCouncil_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolMaoriElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolMaoriElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolMinistryOfEducationLocalOffices", "LastModifiedByPrincipalId", name: "IX_SchoolMinistryOfEducationLocalOffice_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolGeneralElectorates", "LastModifiedByPrincipalId", name: "IX_SchoolGeneralElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolGenders", "LastModifiedByPrincipalId", name: "IX_SchoolGender_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolEducationRegions", "LastModifiedByPrincipalId", name: "IX_SchoolEducationRegion_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolDefinitions", "LastModifiedByPrincipalId", name: "IX_SchoolDefinition_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolDeciles", "LastModifiedByPrincipalId", name: "IX_SchoolDecile_LastModifiedByPrincipalId");
            CreateIndex("Module11.SchoolAuthorities", "LastModifiedByPrincipalId", name: "IX_SchoolAuthority_LastModifiedByPrincipalId");
            CreateIndex("Module11.EducationOrganisations", "LastModifiedByPrincipalId", name: "IX_EducationOrganisation_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyProperties", "LastModifiedByPrincipalId", name: "IX_BodyProperty_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyClaims", "LastModifiedByPrincipalId", name: "IX_BodyClaim_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyChannels", "LastModifiedByPrincipalId", name: "IX_BodyChannel_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyCategories", "LastModifiedByPrincipalId", name: "IX_BodyCategory_LastModifiedByPrincipalId");
            CreateIndex("Module11.BodyAlias", "LastModifiedByPrincipalId", name: "IX_BodyAlias_LastModifiedByPrincipalId");
            CreateIndex("Module11.Bodies", "LastModifiedByPrincipalId", name: "IX_Body_LastModifiedByPrincipalId");
        }
    }
}
