// <auto-generated />
namespace App.Module01.Infrastructure.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Entitiesinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entitiesinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201805220043497_Entities.init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
