namespace App.Module31.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ReferenceDataAddedIndexedTitleAndDescription : DbMigration
    {
        public override void Up()
        {
            AddColumn("Module31.AreaUnits", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.AreaUnits", "Description", c => c.String());
            AddColumn("Module31.AuthorityTypes", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.AuthorityTypes", "Description", c => c.String());
            AddColumn("Module31.CommunityBoards", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.CommunityBoards", "Description", c => c.String());
            AddColumn("Module31.EducationProviderClassifications", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderClassifications", "Description", c => c.String());
            AddColumn("Module31.CoLs", "Title", c => c.String());
            AddColumn("Module31.CoLs", "Description", c => c.String());
            AddColumn("Module31.EducationProviderTypes", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderTypes", "Description", c => c.String());
            AddColumn("Module31.GeneralElectorates", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.GeneralElectorates", "Description", c => c.String());
            AddColumn("Module31.EducationProviderGenders", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderGenders", "Description", c => c.String());
            AddColumn("Module31.EducationProviderYearLevels", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderYearLevels", "Description", c => c.String());
            AddColumn("Module31.LocalOffices", "Title", c => c.String());
            AddColumn("Module31.LocalOffices", "Description", c => c.String());
            AddColumn("Module31.MaoriElectorates", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.MaoriElectorates", "Description", c => c.String());
            AddColumn("Module31.Regions", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.Regions", "Description", c => c.String());
            AddColumn("Module31.RegionalCouncils", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.RegionalCouncils", "Description", c => c.String());
            AddColumn("Module31.SpecialSchoolings", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.SpecialSchoolings", "Description", c => c.String());
            AddColumn("Module31.EducationProviderStatus", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderStatus", "Description", c => c.String());
            AddColumn("Module31.TeacherEducations", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.TeacherEducations", "Description", c => c.String());
            AddColumn("Module31.TerritorialAuthorities", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.TerritorialAuthorities", "Description", c => c.String());
            AddColumn("Module31.UrbanAreas", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.UrbanAreas", "Description", c => c.String());
            AddColumn("Module31.Wards", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.Wards", "Description", c => c.String());
            AddColumn("Module31.RelationshipTypes", "Title", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.RelationshipTypes", "Description", c => c.String());
            CreateIndex("Module31.AreaUnits", "Title", name: "IX_AreaUnit_Title");
            CreateIndex("Module31.AuthorityTypes", "Title", name: "IX_AuthorityType_Title");
            CreateIndex("Module31.CommunityBoards", "Title", name: "IX_CommunityBoard_Title");
            CreateIndex("Module31.EducationProviderClassifications", "Title", name: "IX_EducationProviderClassification_Title");
            CreateIndex("Module31.EducationProviderTypes", "Title", name: "IX_EducationProviderType_Title");
            CreateIndex("Module31.GeneralElectorates", "Title", name: "IX_GeneralElectorate_Title");
            CreateIndex("Module31.EducationProviderGenders", "Title", name: "IX_EducationProviderGender_Title");
            CreateIndex("Module31.EducationProviderYearLevels", "Title", name: "IX_EducationProviderYearLevel_Title");
            CreateIndex("Module31.MaoriElectorates", "Title", name: "IX_MaoriElectorate_Title");
            CreateIndex("Module31.Regions", "Title", name: "IX_Region_Title");
            CreateIndex("Module31.RegionalCouncils", "Title", name: "IX_RegionalCouncil_Title");
            CreateIndex("Module31.SpecialSchoolings", "Title", name: "IX_SpecialSchooling_Title");
            CreateIndex("Module31.EducationProviderStatus", "Title", name: "IX_EducationProviderStatus_Title");
            CreateIndex("Module31.TeacherEducations", "Title", name: "IX_TeacherEducation_Title");
            CreateIndex("Module31.TerritorialAuthorities", "Title", name: "IX_TerritorialAuthority_Title");
            CreateIndex("Module31.UrbanAreas", "Title", name: "IX_UrbanArea_Title");
            CreateIndex("Module31.Wards", "Title", name: "IX_Ward_Title");
            CreateIndex("Module31.RelationshipTypes", "Title", name: "IX_RelationshipType_Title");
            DropColumn("Module31.AreaUnits", "Text");
            DropColumn("Module31.AuthorityTypes", "Text");
            DropColumn("Module31.CommunityBoards", "Text");
            DropColumn("Module31.EducationProviderClassifications", "Text");
            DropColumn("Module31.CoLs", "Text");
            DropColumn("Module31.EducationProviderTypes", "Text");
            DropColumn("Module31.GeneralElectorates", "Text");
            DropColumn("Module31.EducationProviderGenders", "Text");
            DropColumn("Module31.EducationProviderYearLevels", "Text");
            DropColumn("Module31.LocalOffices", "Text");
            DropColumn("Module31.MaoriElectorates", "Text");
            DropColumn("Module31.Regions", "Text");
            DropColumn("Module31.RegionalCouncils", "Text");
            DropColumn("Module31.SpecialSchoolings", "Text");
            DropColumn("Module31.EducationProviderStatus", "Text");
            DropColumn("Module31.TeacherEducations", "Text");
            DropColumn("Module31.TerritorialAuthorities", "Text");
            DropColumn("Module31.UrbanAreas", "Text");
            DropColumn("Module31.Wards", "Text");
            DropColumn("Module31.RelationshipTypes", "Text");
        }
        
        public override void Down()
        {
            AddColumn("Module31.RelationshipTypes", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.Wards", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.UrbanAreas", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.TerritorialAuthorities", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.TeacherEducations", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderStatus", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.SpecialSchoolings", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.RegionalCouncils", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.Regions", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.MaoriElectorates", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.LocalOffices", "Text", c => c.String());
            AddColumn("Module31.EducationProviderYearLevels", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderGenders", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.GeneralElectorates", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.EducationProviderTypes", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.CoLs", "Text", c => c.String());
            AddColumn("Module31.EducationProviderClassifications", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.CommunityBoards", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.AuthorityTypes", "Text", c => c.String(nullable: false, maxLength: 64));
            AddColumn("Module31.AreaUnits", "Text", c => c.String(nullable: false, maxLength: 64));
            DropIndex("Module31.RelationshipTypes", "IX_RelationshipType_Title");
            DropIndex("Module31.Wards", "IX_Ward_Title");
            DropIndex("Module31.UrbanAreas", "IX_UrbanArea_Title");
            DropIndex("Module31.TerritorialAuthorities", "IX_TerritorialAuthority_Title");
            DropIndex("Module31.TeacherEducations", "IX_TeacherEducation_Title");
            DropIndex("Module31.EducationProviderStatus", "IX_EducationProviderStatus_Title");
            DropIndex("Module31.SpecialSchoolings", "IX_SpecialSchooling_Title");
            DropIndex("Module31.RegionalCouncils", "IX_RegionalCouncil_Title");
            DropIndex("Module31.Regions", "IX_Region_Title");
            DropIndex("Module31.MaoriElectorates", "IX_MaoriElectorate_Title");
            DropIndex("Module31.EducationProviderYearLevels", "IX_EducationProviderYearLevel_Title");
            DropIndex("Module31.EducationProviderGenders", "IX_EducationProviderGender_Title");
            DropIndex("Module31.GeneralElectorates", "IX_GeneralElectorate_Title");
            DropIndex("Module31.EducationProviderTypes", "IX_EducationProviderType_Title");
            DropIndex("Module31.EducationProviderClassifications", "IX_EducationProviderClassification_Title");
            DropIndex("Module31.CommunityBoards", "IX_CommunityBoard_Title");
            DropIndex("Module31.AuthorityTypes", "IX_AuthorityType_Title");
            DropIndex("Module31.AreaUnits", "IX_AreaUnit_Title");
            DropColumn("Module31.RelationshipTypes", "Description");
            DropColumn("Module31.RelationshipTypes", "Title");
            DropColumn("Module31.Wards", "Description");
            DropColumn("Module31.Wards", "Title");
            DropColumn("Module31.UrbanAreas", "Description");
            DropColumn("Module31.UrbanAreas", "Title");
            DropColumn("Module31.TerritorialAuthorities", "Description");
            DropColumn("Module31.TerritorialAuthorities", "Title");
            DropColumn("Module31.TeacherEducations", "Description");
            DropColumn("Module31.TeacherEducations", "Title");
            DropColumn("Module31.EducationProviderStatus", "Description");
            DropColumn("Module31.EducationProviderStatus", "Title");
            DropColumn("Module31.SpecialSchoolings", "Description");
            DropColumn("Module31.SpecialSchoolings", "Title");
            DropColumn("Module31.RegionalCouncils", "Description");
            DropColumn("Module31.RegionalCouncils", "Title");
            DropColumn("Module31.Regions", "Description");
            DropColumn("Module31.Regions", "Title");
            DropColumn("Module31.MaoriElectorates", "Description");
            DropColumn("Module31.MaoriElectorates", "Title");
            DropColumn("Module31.LocalOffices", "Description");
            DropColumn("Module31.LocalOffices", "Title");
            DropColumn("Module31.EducationProviderYearLevels", "Description");
            DropColumn("Module31.EducationProviderYearLevels", "Title");
            DropColumn("Module31.EducationProviderGenders", "Description");
            DropColumn("Module31.EducationProviderGenders", "Title");
            DropColumn("Module31.GeneralElectorates", "Description");
            DropColumn("Module31.GeneralElectorates", "Title");
            DropColumn("Module31.EducationProviderTypes", "Description");
            DropColumn("Module31.EducationProviderTypes", "Title");
            DropColumn("Module31.CoLs", "Description");
            DropColumn("Module31.CoLs", "Title");
            DropColumn("Module31.EducationProviderClassifications", "Description");
            DropColumn("Module31.EducationProviderClassifications", "Title");
            DropColumn("Module31.CommunityBoards", "Description");
            DropColumn("Module31.CommunityBoards", "Title");
            DropColumn("Module31.AuthorityTypes", "Description");
            DropColumn("Module31.AuthorityTypes", "Title");
            DropColumn("Module31.AreaUnits", "Description");
            DropColumn("Module31.AreaUnits", "Title");
        }
    }
}
