namespace App.Module3.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class More : DbMigration
    {
        public override void Up()
        {
            AlterColumn("Module3.ExtractWatermarks", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.ExtractWatermarks", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.ExtractWatermarks", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.AreaUnits", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.AreaUnits", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.AreaUnits", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.AuthorityTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.AuthorityTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.AuthorityTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.CommunityBoards", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.CommunityBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.CommunityBoards", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.GeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.GeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.GeneralElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.MaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.MaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.MaoriElectorates", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderStatus", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderStatus", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderStatus", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.Regions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.Regions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.Regions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.RegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.RegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.RegionalCouncils", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.RelationshipTypes", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.RelationshipTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.RelationshipTypes", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderClassifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderClassifications", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderGenders", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderGenders", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderYearLevels", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderYearLevels", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderYearLevels", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.SpecialSchoolings", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.SpecialSchoolings", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.SpecialSchoolings", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.TeacherEducations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.TeacherEducations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.TeacherEducations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.TerritorialAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.TerritorialAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.TerritorialAuthorities", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.UrbanAreas", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.UrbanAreas", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.UrbanAreas", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.Wards", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.Wards", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.Wards", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderLocations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderLocations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderLocations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderLevelGenders", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderLevelGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderLevelGenders", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Module3.EducationProviderProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Module3.EducationProviderProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            CreateIndex("Module3.ExtractWatermarks", "RecordState", name: "IX_ExtractWatermark_RecordState");
            CreateIndex("Module3.ExtractWatermarks", "LastModifiedOnUtc", name: "IX_ExtractWatermark_LastModifiedOnUtc");
            CreateIndex("Module3.ExtractWatermarks", "LastModifiedByPrincipalId", name: "IX_ExtractWatermark_LastModifiedByPrincipalId");
            CreateIndex("Module3.AreaUnits", "TenantFK", name: "IX_AreaUnit_TenantFK");
            CreateIndex("Module3.AreaUnits", "RecordState", name: "IX_AreaUnit_RecordState");
            CreateIndex("Module3.AreaUnits", "LastModifiedOnUtc", name: "IX_AreaUnit_LastModifiedOnUtc");
            CreateIndex("Module3.AreaUnits", "LastModifiedByPrincipalId", name: "IX_AreaUnit_LastModifiedByPrincipalId");
            CreateIndex("Module3.AuthorityTypes", "TenantFK", name: "IX_AuthorityType_TenantFK");
            CreateIndex("Module3.AuthorityTypes", "RecordState", name: "IX_AuthorityType_RecordState");
            CreateIndex("Module3.AuthorityTypes", "LastModifiedOnUtc", name: "IX_AuthorityType_LastModifiedOnUtc");
            CreateIndex("Module3.AuthorityTypes", "LastModifiedByPrincipalId", name: "IX_AuthorityType_LastModifiedByPrincipalId");
            CreateIndex("Module3.CommunityBoards", "TenantFK", name: "IX_CommunityBoard_TenantFK");
            CreateIndex("Module3.CommunityBoards", "RecordState", name: "IX_CommunityBoard_RecordState");
            CreateIndex("Module3.CommunityBoards", "LastModifiedOnUtc", name: "IX_CommunityBoard_LastModifiedOnUtc");
            CreateIndex("Module3.CommunityBoards", "LastModifiedByPrincipalId", name: "IX_CommunityBoard_LastModifiedByPrincipalId");
            CreateIndex("Module3.GeneralElectorates", "TenantFK", name: "IX_GeneralElectorate_TenantFK");
            CreateIndex("Module3.GeneralElectorates", "RecordState", name: "IX_GeneralElectorate_RecordState");
            CreateIndex("Module3.GeneralElectorates", "LastModifiedOnUtc", name: "IX_GeneralElectorate_LastModifiedOnUtc");
            CreateIndex("Module3.GeneralElectorates", "LastModifiedByPrincipalId", name: "IX_GeneralElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module3.MaoriElectorates", "TenantFK", name: "IX_MaoriElectorate_TenantFK");
            CreateIndex("Module3.MaoriElectorates", "RecordState", name: "IX_MaoriElectorate_RecordState");
            CreateIndex("Module3.MaoriElectorates", "LastModifiedOnUtc", name: "IX_MaoriElectorate_LastModifiedOnUtc");
            CreateIndex("Module3.MaoriElectorates", "LastModifiedByPrincipalId", name: "IX_MaoriElectorate_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderStatus", "TenantFK", name: "IX_EducationProviderStatus_TenantFK");
            CreateIndex("Module3.EducationProviderStatus", "RecordState", name: "IX_EducationProviderStatus_RecordState");
            CreateIndex("Module3.EducationProviderStatus", "LastModifiedOnUtc", name: "IX_EducationProviderStatus_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderStatus", "LastModifiedByPrincipalId", name: "IX_EducationProviderStatus_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderTypes", "TenantFK", name: "IX_EducationProviderType_TenantFK");
            CreateIndex("Module3.EducationProviderTypes", "RecordState", name: "IX_EducationProviderType_RecordState");
            CreateIndex("Module3.EducationProviderTypes", "LastModifiedOnUtc", name: "IX_EducationProviderType_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderTypes", "LastModifiedByPrincipalId", name: "IX_EducationProviderType_LastModifiedByPrincipalId");
            CreateIndex("Module3.Regions", "TenantFK", name: "IX_Region_TenantFK");
            CreateIndex("Module3.Regions", "RecordState", name: "IX_Region_RecordState");
            CreateIndex("Module3.Regions", "LastModifiedOnUtc", name: "IX_Region_LastModifiedOnUtc");
            CreateIndex("Module3.Regions", "LastModifiedByPrincipalId", name: "IX_Region_LastModifiedByPrincipalId");
            CreateIndex("Module3.RegionalCouncils", "TenantFK", name: "IX_RegionalCouncil_TenantFK");
            CreateIndex("Module3.RegionalCouncils", "RecordState", name: "IX_RegionalCouncil_RecordState");
            CreateIndex("Module3.RegionalCouncils", "LastModifiedOnUtc", name: "IX_RegionalCouncil_LastModifiedOnUtc");
            CreateIndex("Module3.RegionalCouncils", "LastModifiedByPrincipalId", name: "IX_RegionalCouncil_LastModifiedByPrincipalId");
            CreateIndex("Module3.RelationshipTypes", "TenantFK", name: "IX_RelationshipType_TenantFK");
            CreateIndex("Module3.RelationshipTypes", "RecordState", name: "IX_RelationshipType_RecordState");
            CreateIndex("Module3.RelationshipTypes", "LastModifiedOnUtc", name: "IX_RelationshipType_LastModifiedOnUtc");
            CreateIndex("Module3.RelationshipTypes", "LastModifiedByPrincipalId", name: "IX_RelationshipType_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderClassifications", "TenantFK", name: "IX_EducationProviderClassification_TenantFK");
            CreateIndex("Module3.EducationProviderClassifications", "RecordState", name: "IX_EducationProviderClassification_RecordState");
            CreateIndex("Module3.EducationProviderClassifications", "LastModifiedOnUtc", name: "IX_EducationProviderClassification_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderClassifications", "LastModifiedByPrincipalId", name: "IX_EducationProviderClassification_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderGenders", "TenantFK", name: "IX_EducationProviderGender_TenantFK");
            CreateIndex("Module3.EducationProviderGenders", "RecordState", name: "IX_EducationProviderGender_RecordState");
            CreateIndex("Module3.EducationProviderGenders", "LastModifiedOnUtc", name: "IX_EducationProviderGender_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderGenders", "LastModifiedByPrincipalId", name: "IX_EducationProviderGender_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderYearLevels", "TenantFK", name: "IX_EducationProviderYearLevel_TenantFK");
            CreateIndex("Module3.EducationProviderYearLevels", "RecordState", name: "IX_EducationProviderYearLevel_RecordState");
            CreateIndex("Module3.EducationProviderYearLevels", "LastModifiedOnUtc", name: "IX_EducationProviderYearLevel_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderYearLevels", "LastModifiedByPrincipalId", name: "IX_EducationProviderYearLevel_LastModifiedByPrincipalId");
            CreateIndex("Module3.SpecialSchoolings", "TenantFK", name: "IX_SpecialSchooling_TenantFK");
            CreateIndex("Module3.SpecialSchoolings", "RecordState", name: "IX_SpecialSchooling_RecordState");
            CreateIndex("Module3.SpecialSchoolings", "LastModifiedOnUtc", name: "IX_SpecialSchooling_LastModifiedOnUtc");
            CreateIndex("Module3.SpecialSchoolings", "LastModifiedByPrincipalId", name: "IX_SpecialSchooling_LastModifiedByPrincipalId");
            CreateIndex("Module3.TeacherEducations", "TenantFK", name: "IX_TeacherEducation_TenantFK");
            CreateIndex("Module3.TeacherEducations", "RecordState", name: "IX_TeacherEducation_RecordState");
            CreateIndex("Module3.TeacherEducations", "LastModifiedOnUtc", name: "IX_TeacherEducation_LastModifiedOnUtc");
            CreateIndex("Module3.TeacherEducations", "LastModifiedByPrincipalId", name: "IX_TeacherEducation_LastModifiedByPrincipalId");
            CreateIndex("Module3.TerritorialAuthorities", "TenantFK", name: "IX_TerritorialAuthority_TenantFK");
            CreateIndex("Module3.TerritorialAuthorities", "RecordState", name: "IX_TerritorialAuthority_RecordState");
            CreateIndex("Module3.TerritorialAuthorities", "LastModifiedOnUtc", name: "IX_TerritorialAuthority_LastModifiedOnUtc");
            CreateIndex("Module3.TerritorialAuthorities", "LastModifiedByPrincipalId", name: "IX_TerritorialAuthority_LastModifiedByPrincipalId");
            CreateIndex("Module3.UrbanAreas", "TenantFK", name: "IX_UrbanArea_TenantFK");
            CreateIndex("Module3.UrbanAreas", "RecordState", name: "IX_UrbanArea_RecordState");
            CreateIndex("Module3.UrbanAreas", "LastModifiedOnUtc", name: "IX_UrbanArea_LastModifiedOnUtc");
            CreateIndex("Module3.UrbanAreas", "LastModifiedByPrincipalId", name: "IX_UrbanArea_LastModifiedByPrincipalId");
            CreateIndex("Module3.Wards", "TenantFK", name: "IX_Ward_TenantFK");
            CreateIndex("Module3.Wards", "RecordState", name: "IX_Ward_RecordState");
            CreateIndex("Module3.Wards", "LastModifiedOnUtc", name: "IX_Ward_LastModifiedOnUtc");
            CreateIndex("Module3.Wards", "LastModifiedByPrincipalId", name: "IX_Ward_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderLocations", "TenantFK", name: "IX_EducationProviderLocation_TenantFK");
            CreateIndex("Module3.EducationProviderLocations", "RecordState", name: "IX_EducationProviderLocation_RecordState");
            CreateIndex("Module3.EducationProviderLocations", "LastModifiedOnUtc", name: "IX_EducationProviderLocation_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderLocations", "LastModifiedByPrincipalId", name: "IX_EducationProviderLocation_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderEnrolmentCounts", "TenantFK", name: "IX_EducationProviderEnrolmentCount_TenantFK");
            CreateIndex("Module3.EducationProviderEnrolmentCounts", "RecordState", name: "IX_EducationProviderEnrolmentCount_RecordState");
            CreateIndex("Module3.EducationProviderEnrolmentCounts", "LastModifiedOnUtc", name: "IX_EducationProviderEnrolmentCount_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderEnrolmentCounts", "LastModifiedByPrincipalId", name: "IX_EducationProviderEnrolmentCount_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderLevelGenders", "TenantFK", name: "IX_EducationProviderLevelGender_TenantFK");
            CreateIndex("Module3.EducationProviderLevelGenders", "RecordState", name: "IX_EducationProviderLevelGender_RecordState");
            CreateIndex("Module3.EducationProviderLevelGenders", "LastModifiedOnUtc", name: "IX_EducationProviderLevelGender_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderLevelGenders", "LastModifiedByPrincipalId", name: "IX_EducationProviderLevelGender_LastModifiedByPrincipalId");
            CreateIndex("Module3.EducationProviderProfiles", "TenantFK", name: "IX_EducationProviderProfile_TenantFK");
            CreateIndex("Module3.EducationProviderProfiles", "LastModifiedOnUtc", name: "IX_EducationProviderProfile_LastModifiedOnUtc");
            CreateIndex("Module3.EducationProviderProfiles", "LastModifiedByPrincipalId", name: "IX_EducationProviderProfile_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Module3.EducationProviderProfiles", "IX_EducationProviderProfile_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderProfiles", "IX_EducationProviderProfile_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderProfiles", "IX_EducationProviderProfile_TenantFK");
            DropIndex("Module3.EducationProviderLevelGenders", "IX_EducationProviderLevelGender_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderLevelGenders", "IX_EducationProviderLevelGender_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderLevelGenders", "IX_EducationProviderLevelGender_RecordState");
            DropIndex("Module3.EducationProviderLevelGenders", "IX_EducationProviderLevelGender_TenantFK");
            DropIndex("Module3.EducationProviderEnrolmentCounts", "IX_EducationProviderEnrolmentCount_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderEnrolmentCounts", "IX_EducationProviderEnrolmentCount_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderEnrolmentCounts", "IX_EducationProviderEnrolmentCount_RecordState");
            DropIndex("Module3.EducationProviderEnrolmentCounts", "IX_EducationProviderEnrolmentCount_TenantFK");
            DropIndex("Module3.EducationProviderLocations", "IX_EducationProviderLocation_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderLocations", "IX_EducationProviderLocation_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderLocations", "IX_EducationProviderLocation_RecordState");
            DropIndex("Module3.EducationProviderLocations", "IX_EducationProviderLocation_TenantFK");
            DropIndex("Module3.Wards", "IX_Ward_LastModifiedByPrincipalId");
            DropIndex("Module3.Wards", "IX_Ward_LastModifiedOnUtc");
            DropIndex("Module3.Wards", "IX_Ward_RecordState");
            DropIndex("Module3.Wards", "IX_Ward_TenantFK");
            DropIndex("Module3.UrbanAreas", "IX_UrbanArea_LastModifiedByPrincipalId");
            DropIndex("Module3.UrbanAreas", "IX_UrbanArea_LastModifiedOnUtc");
            DropIndex("Module3.UrbanAreas", "IX_UrbanArea_RecordState");
            DropIndex("Module3.UrbanAreas", "IX_UrbanArea_TenantFK");
            DropIndex("Module3.TerritorialAuthorities", "IX_TerritorialAuthority_LastModifiedByPrincipalId");
            DropIndex("Module3.TerritorialAuthorities", "IX_TerritorialAuthority_LastModifiedOnUtc");
            DropIndex("Module3.TerritorialAuthorities", "IX_TerritorialAuthority_RecordState");
            DropIndex("Module3.TerritorialAuthorities", "IX_TerritorialAuthority_TenantFK");
            DropIndex("Module3.TeacherEducations", "IX_TeacherEducation_LastModifiedByPrincipalId");
            DropIndex("Module3.TeacherEducations", "IX_TeacherEducation_LastModifiedOnUtc");
            DropIndex("Module3.TeacherEducations", "IX_TeacherEducation_RecordState");
            DropIndex("Module3.TeacherEducations", "IX_TeacherEducation_TenantFK");
            DropIndex("Module3.SpecialSchoolings", "IX_SpecialSchooling_LastModifiedByPrincipalId");
            DropIndex("Module3.SpecialSchoolings", "IX_SpecialSchooling_LastModifiedOnUtc");
            DropIndex("Module3.SpecialSchoolings", "IX_SpecialSchooling_RecordState");
            DropIndex("Module3.SpecialSchoolings", "IX_SpecialSchooling_TenantFK");
            DropIndex("Module3.EducationProviderYearLevels", "IX_EducationProviderYearLevel_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderYearLevels", "IX_EducationProviderYearLevel_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderYearLevels", "IX_EducationProviderYearLevel_RecordState");
            DropIndex("Module3.EducationProviderYearLevels", "IX_EducationProviderYearLevel_TenantFK");
            DropIndex("Module3.EducationProviderGenders", "IX_EducationProviderGender_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderGenders", "IX_EducationProviderGender_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderGenders", "IX_EducationProviderGender_RecordState");
            DropIndex("Module3.EducationProviderGenders", "IX_EducationProviderGender_TenantFK");
            DropIndex("Module3.EducationProviderClassifications", "IX_EducationProviderClassification_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderClassifications", "IX_EducationProviderClassification_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderClassifications", "IX_EducationProviderClassification_RecordState");
            DropIndex("Module3.EducationProviderClassifications", "IX_EducationProviderClassification_TenantFK");
            DropIndex("Module3.RelationshipTypes", "IX_RelationshipType_LastModifiedByPrincipalId");
            DropIndex("Module3.RelationshipTypes", "IX_RelationshipType_LastModifiedOnUtc");
            DropIndex("Module3.RelationshipTypes", "IX_RelationshipType_RecordState");
            DropIndex("Module3.RelationshipTypes", "IX_RelationshipType_TenantFK");
            DropIndex("Module3.RegionalCouncils", "IX_RegionalCouncil_LastModifiedByPrincipalId");
            DropIndex("Module3.RegionalCouncils", "IX_RegionalCouncil_LastModifiedOnUtc");
            DropIndex("Module3.RegionalCouncils", "IX_RegionalCouncil_RecordState");
            DropIndex("Module3.RegionalCouncils", "IX_RegionalCouncil_TenantFK");
            DropIndex("Module3.Regions", "IX_Region_LastModifiedByPrincipalId");
            DropIndex("Module3.Regions", "IX_Region_LastModifiedOnUtc");
            DropIndex("Module3.Regions", "IX_Region_RecordState");
            DropIndex("Module3.Regions", "IX_Region_TenantFK");
            DropIndex("Module3.EducationProviderTypes", "IX_EducationProviderType_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderTypes", "IX_EducationProviderType_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderTypes", "IX_EducationProviderType_RecordState");
            DropIndex("Module3.EducationProviderTypes", "IX_EducationProviderType_TenantFK");
            DropIndex("Module3.EducationProviderStatus", "IX_EducationProviderStatus_LastModifiedByPrincipalId");
            DropIndex("Module3.EducationProviderStatus", "IX_EducationProviderStatus_LastModifiedOnUtc");
            DropIndex("Module3.EducationProviderStatus", "IX_EducationProviderStatus_RecordState");
            DropIndex("Module3.EducationProviderStatus", "IX_EducationProviderStatus_TenantFK");
            DropIndex("Module3.MaoriElectorates", "IX_MaoriElectorate_LastModifiedByPrincipalId");
            DropIndex("Module3.MaoriElectorates", "IX_MaoriElectorate_LastModifiedOnUtc");
            DropIndex("Module3.MaoriElectorates", "IX_MaoriElectorate_RecordState");
            DropIndex("Module3.MaoriElectorates", "IX_MaoriElectorate_TenantFK");
            DropIndex("Module3.GeneralElectorates", "IX_GeneralElectorate_LastModifiedByPrincipalId");
            DropIndex("Module3.GeneralElectorates", "IX_GeneralElectorate_LastModifiedOnUtc");
            DropIndex("Module3.GeneralElectorates", "IX_GeneralElectorate_RecordState");
            DropIndex("Module3.GeneralElectorates", "IX_GeneralElectorate_TenantFK");
            DropIndex("Module3.CommunityBoards", "IX_CommunityBoard_LastModifiedByPrincipalId");
            DropIndex("Module3.CommunityBoards", "IX_CommunityBoard_LastModifiedOnUtc");
            DropIndex("Module3.CommunityBoards", "IX_CommunityBoard_RecordState");
            DropIndex("Module3.CommunityBoards", "IX_CommunityBoard_TenantFK");
            DropIndex("Module3.AuthorityTypes", "IX_AuthorityType_LastModifiedByPrincipalId");
            DropIndex("Module3.AuthorityTypes", "IX_AuthorityType_LastModifiedOnUtc");
            DropIndex("Module3.AuthorityTypes", "IX_AuthorityType_RecordState");
            DropIndex("Module3.AuthorityTypes", "IX_AuthorityType_TenantFK");
            DropIndex("Module3.AreaUnits", "IX_AreaUnit_LastModifiedByPrincipalId");
            DropIndex("Module3.AreaUnits", "IX_AreaUnit_LastModifiedOnUtc");
            DropIndex("Module3.AreaUnits", "IX_AreaUnit_RecordState");
            DropIndex("Module3.AreaUnits", "IX_AreaUnit_TenantFK");
            DropIndex("Module3.ExtractWatermarks", "IX_ExtractWatermark_LastModifiedByPrincipalId");
            DropIndex("Module3.ExtractWatermarks", "IX_ExtractWatermark_LastModifiedOnUtc");
            DropIndex("Module3.ExtractWatermarks", "IX_ExtractWatermark_RecordState");
            AlterColumn("Module3.EducationProviderProfiles", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderProfiles", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderLevelGenders", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderLevelGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderLevelGenders", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderEnrolmentCounts", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderLocations", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderLocations", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderLocations", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.Wards", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.Wards", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.Wards", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.UrbanAreas", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.UrbanAreas", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.UrbanAreas", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.TerritorialAuthorities", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.TerritorialAuthorities", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.TerritorialAuthorities", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.TeacherEducations", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.TeacherEducations", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.TeacherEducations", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.SpecialSchoolings", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.SpecialSchoolings", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.SpecialSchoolings", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderYearLevels", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderYearLevels", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderYearLevels", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderGenders", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderGenders", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderGenders", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderClassifications", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderClassifications", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.RelationshipTypes", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.RelationshipTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.RelationshipTypes", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.RegionalCouncils", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.RegionalCouncils", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.RegionalCouncils", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.Regions", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.Regions", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.Regions", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderTypes", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderTypes", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderStatus", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.EducationProviderStatus", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.EducationProviderStatus", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.MaoriElectorates", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.MaoriElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.MaoriElectorates", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.GeneralElectorates", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.GeneralElectorates", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.GeneralElectorates", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.CommunityBoards", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.CommunityBoards", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.CommunityBoards", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.AuthorityTypes", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.AuthorityTypes", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.AuthorityTypes", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.AreaUnits", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.AreaUnits", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.AreaUnits", "CreatedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.ExtractWatermarks", "DeletedByPrincipalId", c => c.String());
            AlterColumn("Module3.ExtractWatermarks", "LastModifiedByPrincipalId", c => c.String(nullable: false));
            AlterColumn("Module3.ExtractWatermarks", "CreatedByPrincipalId", c => c.String(nullable: false));
        }
    }
}
