namespace App.Core.Infrastructure.Db.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EntitiesPrincipalLengthUpdate : DbMigration
    {
        public override void Up()
        {
            DropIndex("Core.MediaMetadatas", "IX_MediaMetadata_LastModifiedByPrincipalId");
            DropIndex("Core.DataClassifications", "IX_DataClassification_LastModifiedByPrincipalId");
            DropIndex("Core.Notifications", "IX_Notification_LastModifiedByPrincipalId");
            DropIndex("Core.SessionOperations", "IX_SessionOperation_LastModifiedByPrincipalId");
            DropIndex("Core.Sessions", "IX_Session_LastModifiedByPrincipalId");
            DropIndex("Core.Principals", "IX_Principal_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalCategories", "IX_PrincipalCategory_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalClaims", "IX_PrincipalClaim_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalLogins", "IX_PrincipalLogin_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProperties", "IX_PrincipalProperty_LastModifiedByPrincipalId");
            DropIndex("Core.SystemRoles", "IX_SystemRole_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalTags", "IX_PrincipalTag_LastModifiedByPrincipalId");
            DropIndex("Core.Tenants", "IX_Tenant_LastModifiedByPrincipalId");
            DropIndex("Core.TenantClaims", "IX_TenantClaim_LastModifiedByPrincipalId");
            DropIndex("Core.TenantProperties", "IX_TenantProperty_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfileServiceOfferingAllocations", "IX_PrincipalServiceProfileServiceOfferingAllocation_LastModifiedByPrincipalId");
            DropIndex("Core.ServiceOfferingDefinitions", "IX_ServiceOfferingDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.ServiceDefinitions", "IX_ServiceDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfiles", "IX_PrincipalServiceProfile_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfileServicePlanAllocations", "IX_PrincipalServiceProfileServicePlanAllocation_LastModifiedByPrincipalId");
            DropIndex("Core.ServicePlanDefinitions", "IX_ServicePlanDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfiles", "IX_TenancySecurityProfile_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileRoleGroups", "IX_TenancySecurityProfileRoleGroup_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileAccountRoles", "IX_TenancySecurityProfileAccountRole_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfilePermissions", "IX_TenancySecurityProfilePermission_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "IX_TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "IX_TenancySecurityProfileTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            DropIndex("Core.DataTokens", "IX_DataToken_LastModifiedByPrincipalId");
            DropIndex("Core.ExceptionRecords", "IX_ExceptionRecord_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfiles", "IX_PrincipalProfile_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileCategories", "IX_PrincipalProfileCategory_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileClaims", "IX_PrincipalProfileClaim_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileProperties", "IX_PrincipalProfileProperty_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileTags", "IX_PrincipalProfileTag_LastModifiedByPrincipalId");
            AlterColumn("Core.MediaMetadatas", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.MediaMetadatas", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.MediaMetadatas", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.DataClassifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.DataClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.DataClassifications", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.Notifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Notifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Notifications", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.SessionOperations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.SessionOperations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.SessionOperations", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.Sessions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Sessions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Sessions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.Principals", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Principals", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Principals", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalCategories", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalClaims", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalLogins", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalLogins", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalLogins", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProperties", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.SystemRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.SystemRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.SystemRoles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalTags", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalTags", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalTags", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.Tenants", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Tenants", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.Tenants", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenantClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenantClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenantClaims", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenantProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenantProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenantProperties", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.ServiceOfferingDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServiceOfferingDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServiceOfferingDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.ServiceDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServiceDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServiceDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.ServicePlanDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServicePlanDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ServicePlanDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfilePermissions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfilePermissions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfilePermissions", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.DataTokens", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.DataTokens", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.DataTokens", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.ExceptionRecords", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ExceptionRecords", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.ExceptionRecords", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProfileCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileCategories", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProfileClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileClaims", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProfileProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileProperties", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            AlterColumn("Core.PrincipalProfileTags", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileTags", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("Core.PrincipalProfileTags", "DeletedByPrincipalId", c => c.String(maxLength: 36));
            CreateIndex("Core.MediaMetadatas", "LastModifiedByPrincipalId", name: "IX_MediaMetadata_LastModifiedByPrincipalId");
            CreateIndex("Core.DataClassifications", "LastModifiedByPrincipalId", name: "IX_DataClassification_LastModifiedByPrincipalId");
            CreateIndex("Core.Notifications", "LastModifiedByPrincipalId", name: "IX_Notification_LastModifiedByPrincipalId");
            CreateIndex("Core.SessionOperations", "LastModifiedByPrincipalId", name: "IX_SessionOperation_LastModifiedByPrincipalId");
            CreateIndex("Core.Sessions", "LastModifiedByPrincipalId", name: "IX_Session_LastModifiedByPrincipalId");
            CreateIndex("Core.Principals", "LastModifiedByPrincipalId", name: "IX_Principal_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalCategories", "LastModifiedByPrincipalId", name: "IX_PrincipalCategory_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalClaims", "LastModifiedByPrincipalId", name: "IX_PrincipalClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalLogins", "LastModifiedByPrincipalId", name: "IX_PrincipalLogin_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProperties", "LastModifiedByPrincipalId", name: "IX_PrincipalProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.SystemRoles", "LastModifiedByPrincipalId", name: "IX_SystemRole_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalTags", "LastModifiedByPrincipalId", name: "IX_PrincipalTag_LastModifiedByPrincipalId");
            CreateIndex("Core.Tenants", "LastModifiedByPrincipalId", name: "IX_Tenant_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantClaims", "LastModifiedByPrincipalId", name: "IX_TenantClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantProperties", "LastModifiedByPrincipalId", name: "IX_TenantProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfileServiceOfferingAllocations", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfileServiceOfferingAllocation_LastModifiedByPrincipalId");
            CreateIndex("Core.ServiceOfferingDefinitions", "LastModifiedByPrincipalId", name: "IX_ServiceOfferingDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.ServiceDefinitions", "LastModifiedByPrincipalId", name: "IX_ServiceDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfiles", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfileServicePlanAllocations", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfileServicePlanAllocation_LastModifiedByPrincipalId");
            CreateIndex("Core.ServicePlanDefinitions", "LastModifiedByPrincipalId", name: "IX_ServicePlanDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfiles", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileRoleGroups", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileRoleGroup_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileAccountRoles", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileAccountRole_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfilePermissions", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfilePermission_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            CreateIndex("Core.DataTokens", "LastModifiedByPrincipalId", name: "IX_DataToken_LastModifiedByPrincipalId");
            CreateIndex("Core.ExceptionRecords", "LastModifiedByPrincipalId", name: "IX_ExceptionRecord_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfiles", "LastModifiedByPrincipalId", name: "IX_PrincipalProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileCategories", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileCategory_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileClaims", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileProperties", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileTags", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileTag_LastModifiedByPrincipalId");
        }
        
        public override void Down()
        {
            DropIndex("Core.PrincipalProfileTags", "IX_PrincipalProfileTag_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileProperties", "IX_PrincipalProfileProperty_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileClaims", "IX_PrincipalProfileClaim_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfileCategories", "IX_PrincipalProfileCategory_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProfiles", "IX_PrincipalProfile_LastModifiedByPrincipalId");
            DropIndex("Core.ExceptionRecords", "IX_ExceptionRecord_LastModifiedByPrincipalId");
            DropIndex("Core.DataTokens", "IX_DataToken_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "IX_TenancySecurityProfileTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "IX_TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfilePermissions", "IX_TenancySecurityProfilePermission_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileAccountRoles", "IX_TenancySecurityProfileAccountRole_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfileRoleGroups", "IX_TenancySecurityProfileRoleGroup_LastModifiedByPrincipalId");
            DropIndex("Core.TenancySecurityProfiles", "IX_TenancySecurityProfile_LastModifiedByPrincipalId");
            DropIndex("Core.ServicePlanDefinitions", "IX_ServicePlanDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfileServicePlanAllocations", "IX_PrincipalServiceProfileServicePlanAllocation_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfiles", "IX_PrincipalServiceProfile_LastModifiedByPrincipalId");
            DropIndex("Core.ServiceDefinitions", "IX_ServiceDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.ServiceOfferingDefinitions", "IX_ServiceOfferingDefinition_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalServiceProfileServiceOfferingAllocations", "IX_PrincipalServiceProfileServiceOfferingAllocation_LastModifiedByPrincipalId");
            DropIndex("Core.TenantProperties", "IX_TenantProperty_LastModifiedByPrincipalId");
            DropIndex("Core.TenantClaims", "IX_TenantClaim_LastModifiedByPrincipalId");
            DropIndex("Core.Tenants", "IX_Tenant_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalTags", "IX_PrincipalTag_LastModifiedByPrincipalId");
            DropIndex("Core.SystemRoles", "IX_SystemRole_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalProperties", "IX_PrincipalProperty_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalLogins", "IX_PrincipalLogin_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalClaims", "IX_PrincipalClaim_LastModifiedByPrincipalId");
            DropIndex("Core.PrincipalCategories", "IX_PrincipalCategory_LastModifiedByPrincipalId");
            DropIndex("Core.Principals", "IX_Principal_LastModifiedByPrincipalId");
            DropIndex("Core.Sessions", "IX_Session_LastModifiedByPrincipalId");
            DropIndex("Core.SessionOperations", "IX_SessionOperation_LastModifiedByPrincipalId");
            DropIndex("Core.Notifications", "IX_Notification_LastModifiedByPrincipalId");
            DropIndex("Core.DataClassifications", "IX_DataClassification_LastModifiedByPrincipalId");
            DropIndex("Core.MediaMetadatas", "IX_MediaMetadata_LastModifiedByPrincipalId");
            AlterColumn("Core.PrincipalProfileTags", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProfileTags", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileTags", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProfileProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProfileClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileCategories", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProfileCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfileCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ExceptionRecords", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataTokens", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.DataTokens", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataTokens", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfilePermissions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfilePermissions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfilePermissions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileAccountRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfileRoleGroups", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenancySecurityProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenancySecurityProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServicePlanDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.ServicePlanDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServicePlanDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServicePlanAllocations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfiles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfiles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfiles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServiceDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.ServiceDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServiceDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServiceOfferingDefinitions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.ServiceOfferingDefinitions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.ServiceOfferingDefinitions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalServiceProfileServiceOfferingAllocations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenantProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.TenantClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.TenantClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Tenants", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Tenants", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Tenants", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalTags", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalTags", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalTags", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SystemRoles", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.SystemRoles", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SystemRoles", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalProperties", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalLogins", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalClaims", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.PrincipalCategories", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Principals", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Principals", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Principals", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Sessions", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Sessions", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Sessions", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SessionOperations", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.SessionOperations", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.SessionOperations", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Notifications", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.Notifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.Notifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataClassifications", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.DataClassifications", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.DataClassifications", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.MediaMetadatas", "DeletedByPrincipalId", c => c.String(maxLength: 32));
            AlterColumn("Core.MediaMetadatas", "LastModifiedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("Core.MediaMetadatas", "CreatedByPrincipalId", c => c.String(nullable: false, maxLength: 32));
            CreateIndex("Core.PrincipalProfileTags", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileTag_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileProperties", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileClaims", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfileCategories", "LastModifiedByPrincipalId", name: "IX_PrincipalProfileCategory_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProfiles", "LastModifiedByPrincipalId", name: "IX_PrincipalProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.ExceptionRecords", "LastModifiedByPrincipalId", name: "IX_ExceptionRecord_LastModifiedByPrincipalId");
            CreateIndex("Core.DataTokens", "LastModifiedByPrincipalId", name: "IX_DataToken_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignments", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileRoleTenancySecurityProfilePermissionAssignment_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfilePermissions", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfilePermission_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileAccountRoles", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileAccountRole_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfileRoleGroups", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfileRoleGroup_LastModifiedByPrincipalId");
            CreateIndex("Core.TenancySecurityProfiles", "LastModifiedByPrincipalId", name: "IX_TenancySecurityProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.ServicePlanDefinitions", "LastModifiedByPrincipalId", name: "IX_ServicePlanDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfileServicePlanAllocations", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfileServicePlanAllocation_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfiles", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfile_LastModifiedByPrincipalId");
            CreateIndex("Core.ServiceDefinitions", "LastModifiedByPrincipalId", name: "IX_ServiceDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.ServiceOfferingDefinitions", "LastModifiedByPrincipalId", name: "IX_ServiceOfferingDefinition_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalServiceProfileServiceOfferingAllocations", "LastModifiedByPrincipalId", name: "IX_PrincipalServiceProfileServiceOfferingAllocation_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantProperties", "LastModifiedByPrincipalId", name: "IX_TenantProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.TenantClaims", "LastModifiedByPrincipalId", name: "IX_TenantClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.Tenants", "LastModifiedByPrincipalId", name: "IX_Tenant_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalTags", "LastModifiedByPrincipalId", name: "IX_PrincipalTag_LastModifiedByPrincipalId");
            CreateIndex("Core.SystemRoles", "LastModifiedByPrincipalId", name: "IX_SystemRole_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalProperties", "LastModifiedByPrincipalId", name: "IX_PrincipalProperty_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalLogins", "LastModifiedByPrincipalId", name: "IX_PrincipalLogin_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalClaims", "LastModifiedByPrincipalId", name: "IX_PrincipalClaim_LastModifiedByPrincipalId");
            CreateIndex("Core.PrincipalCategories", "LastModifiedByPrincipalId", name: "IX_PrincipalCategory_LastModifiedByPrincipalId");
            CreateIndex("Core.Principals", "LastModifiedByPrincipalId", name: "IX_Principal_LastModifiedByPrincipalId");
            CreateIndex("Core.Sessions", "LastModifiedByPrincipalId", name: "IX_Session_LastModifiedByPrincipalId");
            CreateIndex("Core.SessionOperations", "LastModifiedByPrincipalId", name: "IX_SessionOperation_LastModifiedByPrincipalId");
            CreateIndex("Core.Notifications", "LastModifiedByPrincipalId", name: "IX_Notification_LastModifiedByPrincipalId");
            CreateIndex("Core.DataClassifications", "LastModifiedByPrincipalId", name: "IX_DataClassification_LastModifiedByPrincipalId");
            CreateIndex("Core.MediaMetadatas", "LastModifiedByPrincipalId", name: "IX_MediaMetadata_LastModifiedByPrincipalId");
        }
    }
}
